[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/product-womenswear"
  to = "/product-womenswear.html"
  status = 200

[[redirects]]
  from = "/product-menswear"
  to = "/product-menswear.html"
  status = 200

[[redirects]]
  from = "/our-team"
  to = "/our-team.html"
  status = 200

[[redirects]]
  from = "/contact-us"
  to = "/contact-us.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200